name: generate-release

on:
  push:
    branches:
      - master

jobs:
  generate_release:
    runs-on: ubuntu-latest
    name: Generate release
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-release"
        prerelease: false
        title: "Latest Release"
